Allow zipped data upload

diff --git a/.github/workflows/upload-data.yml b/.github/workflows/upload-data.yml
--- a/.github/workflows/upload-data.yml
+++ b/.github/workflows/upload-data.yml
@@ -14,6 +14,15 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: upload
+      - name: Extract data
+        run: |
+          if [ -f data.zip ]; then
+            unzip -o data.zip
+          fi
+          if [ ! -f data.json ]; then
+            echo "Missing data file."
+            exit 1
+          fi
       - name: Upload data
         uses: actions/upload-artifact@v4
         with:
